gui:
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#585b70"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
  showIcons: true
  nerdFontsVersion: "3"
  border: rounded
  sidePanelWidth: 0.25

git:
  paging:
    colorArg: always
    pager: delta --side-by-side --line-numbers --paging=never
